# Generated by Django 2.1.4 on 2018-12-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(default='localhost', max_length=20)),
                ('subject', models.CharField(default='subject', max_length=20)),
                ('mailfrom', models.CharField(default='', max_length=30)),
                ('mailto', models.CharField(default='', max_length=30)),
                ('mailtext', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
