# Generated by Django 2.1.4 on 2018-12-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20181208_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
