# Generated by Django 2.1.4 on 2018-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0003_mails_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcptGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('GroupName', models.CharField(default='新建分组', max_length=50)),
                ('GroupMembers', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
