# Generated by Django 2.1.4 on 2018-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_rcptgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcptGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('GroupName', models.CharField(default='新建分组', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='RcptGroups_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(default='', max_length=50)),
                ('MembersAddress', models.CharField(default='', max_length=30)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RcptMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=4)),
                ('mailAddress', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
